### ISSUE TITLE
Missing Adamas Space Station

### ISSUE THREAD

**Issue by Karazura** [toilethinges/Adamas-Project#2]
Okay so I've looked in the files and tried to figure out how to get this mini story arc started and found I need to find the station listed below and know that it is located in Ed Andol.  Upon arriving in the system the space station is supposed to be in,  it is nowhere to be found nor is the nova that is supposed to be in the center of the system. I would like help troubleshooting this so I can get it added to the system and work on this story.
object Dolthtleh
		sprite planet/station1adm
		distance 2344.52
		period 1096.5
		object
			sprite planet/rock7
			distance 224
			period 16.7034

**Comment by toilethinges** [comment]
aba71ac should fix this and add backwards compatibility for you. Land on a planet and go back to Ed Andol, the station and star should be there.

**Comment by Karazura** [comment]
Backwards compatibility doesn't seem to be taking on the two characters I already have. Might work on a new character though. Would take a couple days minimum of grinding to tell if I do the story properly.

**Comment by kestrel1110** [comment]
All I know is that in my coming PR it is fixed.

**Comment by kestrel1110** [comment]
Fixed.

**Comment by toilethinges** [comment]
This bug is fixed in the current version, but has no backwards compatibility.

If you want it fixed on a file where you already opened the wormhole, add
![image](https://user-images.githubusercontent.com/16909765/83339560-d2941100-a294-11ea-8c92-6e0b47d8870f.png)

under the system "Ed Andol" in changes in your save file. It should look like this:
![image](https://user-images.githubusercontent.com/16909765/83339556-c9a33f80-a294-11ea-930e-f3ecfa1aef7f.png)

edit: rip, Git's code blocks didn't maintain my tabs. Will fix shortly.

edit2: Here's a version to copy and paste if you want it:
```		
		object Dolthtleh
			sprite planet/station1adm
			distance 2344.52
			period 1096.5
			object
				sprite planet/rock7
				distance 224
				period 16.7034
```
